var words = [];
var easyWords = [
    "eye",
    "bat",
    "cheese",
    "plant",
    "alive",
    "neck",
    "train",
    "coat",
    "baby",
    "ear",
    "milk",
    "stairs",
    "smile",
    "triangle",
    "baseball",
    "sun",
    "elephant",
    "person",
    "lollipop",
    "balloon",
    "cube",
    "button",
    "lips",
    "orange",
    "ladybug",
    "night",
    "circle",
    "clock",
    "bone",
    "ghost",
    "computer",
    "cat",
    "family",
    "sea turtle",
    "ants",
    "heart",
    "football",
    "music",
    "shoe",
    "lamp",
    "flower",
    "arm",
    "bumblebee",
    "ice cream cone",
    "spider",
    "tree",
    "basketball",
    "bounce",
    "blocks",
    "desk",
    "kite",
    "bug",
    "monkey",
    "river",
    "bench",
    "pencil",
    "swimming pool",
    "rocket",
    "diamond",
    "water",
    "cloud",
    "seashell",
    "coin",
    "bus",
    "rock",
    "swing",
    "door",
    "bathroom",
    "nail",
    "angel",
    "apple",
    "bowl",
    "dog",
    "chair",
    "jar",
    "camera",
    "candy",
    "rain",
    "inchworm",
    "mouse",
    "island",
    "robot",
    "feather",
    "nose",
    "roly poly\\/pill bug\\/doodle bug",
    "worm",
    "chimney",
    "cookie",
    "pie",
    "zoo",
    "owl",
    "sea",
    "backpack",
    "ball",
    "suitcase",
    "flag",
    "drum",
    "cow",
    "hippo",
    "oval",
    "box",
    "spider web",
    "boat",
    "crayon",
    "truck",
    "lemon",
    "frog",
    "feet",
    "man",
    "octopus",
    "cup",
    "ring",
    "fork",
    "fish",
    "woman",
    "dinosaur",
    "daisy",
    "dream",
    "monster",
    "boy",
    "motorcycle",
    "key",
    "glasses",
    "snowman",
    "curl",
    "bracelet",
    "skateboard",
    "sunglasses",
    "broom",
    "legs",
    "line",
    "candle",
    "table",
    "crab",
    "leaf",
    "bird",
    "mountains",
    "bridge",
    "duck",
    "horse",
    "mountain",
    "knee",
    "float",
    "fly",
    "pen",
    "Mickey Mouse",
    "ship",
    "banana",
    "bell",
    "snail",
    "hand",
    "Earth",
    "finger",
    "helicopter",
    "grapes",
    "slide",
    "eyes",
    "ant",
    "bunny",
    "lion",
    "girl",
    "snowflake",
    "jacket",
    "giraffe",
    "snake",
    "socks",
    "pants",
    "lizard",
    "starfish",
    "purse",
    "square",
    "mitten",
    "blanket",
    "house",
    "mouth",
    "bike",
    "beak",
    "window",
    "light",
    "kitten",
    "cupcake",
    "bee",
    "pillow",
    "carrot",
    "book",
    "sheep",
    "crack",
    "whale",
    "rainbow",
    "caterpillar",
    "jellyfish",
    "leg",
    "ears",
    "jail",
    "bread",
    "zigzag",
    "butterfly",
    "rabbit",
    "ocean",
    "corn"
]
var mediumWords = [
    "parka",
    "cobra",
    "rowboat",
    "tissue",
    "blueprint",
    "fan",
    "penguin",
    "toaster",
    "truck",
    "TV",
    "claw",
    "doghouse",
    "cheek",
    "forest",
    "crack",
    "rain",
    "kayak",
    "cobweb",
    "powder",
    "peck",
    "beaver",
    "harp",
    "wood",
    "island",
    "orphan",
    "jet ski",
    "meteor",
    "iron",
    "outer space",
    "t-shirt",
    "tower",
    "quilt",
    "teapot",
    "dominoes",
    "bus",
    "hail",
    "lawnmower",
    "dirt",
    "monkey",
    "sidekick",
    "notebook",
    "sister",
    "extension cord",
    "city",
    "honey",
    "platypus",
    "party",
    "deer",
    "mailman",
    "cheeseburger",
    "saltwater",
    "sword",
    "seahorse",
    "trunk",
    "hummingbird",
    "puppet",
    "room",
    "outside",
    "trophy",
    "wallet",
    "aunt",
    "fork",
    "rocking chair",
    "coil",
    "girlfriend",
    "school",
    "stoplight",
    "sign",
    "third plate",
    "waterfall",
    "cockroach",
    "stem",
    "librarian",
    "snail",
    "piranha",
    "shape",
    "torch",
    "braid",
    "aquarium",
    "cucumber",
    "silverware",
    "north",
    "crumb",
    "scale",
    "cactus",
    "spool",
    "sky",
    "flagpole",
    "shelf",
    "germ",
    "neck",
    "root",
    "electrical outlet",
    "fire hydrant",
    "middle",
    "flamingo",
    "trash can",
    "cracker",
    "bacteria",
    "corndog",
    "spoon",
    "constellation",
    "ferry",
    "shoulder",
    "limousine",
    "lamp",
    "day",
    "napkin",
    "package",
    "vegetable",
    "fist",
    "newlywed",
    "french fries",
    "tiger",
    "page",
    "gum",
    "mouse pad",
    "crow",
    "church",
    "chef",
    "toilet paper",
    "bag",
    "curb",
    "net",
    "tongue",
    "frog",
    "insect",
    "pie",
    "hotel",
    "chin",
    "piano",
    "spider web",
    "pond",
    "wedge",
    "donkey",
    "jelly",
    "see",
    "rainstorm",
    "earmuffs",
    "narwhal",
    "owl",
    "saw",
    "porthole",
    "scissors",
    "cabin",
    "garbage",
    "cork",
    "coast",
    "pirate",
    "lawn mower",
    "dump truck",
    "gift",
    "wheelbarrow",
    "kite",
    "happy",
    "fishing pole",
    "unite",
    "starfish",
    "astronaut",
    "brush",
    "hen",
    "lunchbox",
    "bottle",
    "pilot",
    "magazine",
    "gasoline",
    "seaweed",
    "Jupiter",
    "snowball",
    "rake",
    "toe",
    "field",
    "pizza",
    "seal",
    "ring",
    "horn",
    "curve",
    "blowfish",
    "connect",
    "bubble",
    "windmill",
    "hook",
    "rainbow",
    "state",
    "hiss",
    "unicycle",
    "easel",
    "road",
    "mop",
    "jail",
    "inch",
    "hippopotamus",
    "pumpkin",
    "dimple",
    "summer",
    "pancake",
    "ladder",
    "drawer",
    "stomach",
    "yacht",
    "volcano",
    "flashlight",
    "sink",
    "orange",
    "lobster",
    "spare",
    "shade",
    "seed",
    "soup",
    "oven",
    "shallow",
    "breakfast",
    "paperclip",
    "parachuting",
    "pen",
    "suitcase",
    "corn dog",
    "brick",
    "bakery",
    "deep",
    "fanny pack",
    "soda",
    "mini blinds",
    "sandal",
    "spring",
    "snowflake",
    "curtains",
    "cash",
    "beach",
    "dad",
    "dustpan",
    "locket",
    "password",
    "popsicle",
    "prince",
    "rattle",
    "coyote",
    "stove",
    "rhinoceros",
    "hair dryer",
    "tuba",
    "firefighter",
    "scarecrow",
    "paint",
    "lake",
    "yarn",
    "coat",
    "glove",
    "windshield",
    "pantry",
    "drink",
    "scar",
    "trapeze",
    "dolphin",
    "forehead",
    "match",
    "newborn",
    "open",
    "dock",
    "sheep",
    "chimney",
    "spot",
    "unicorn",
    "peanut",
    "gingerbread man",
    "pretzel",
    "gap",
    "grill",
    "cemetery",
    "sunflower",
    "strawberry",
    "dragonfly",
    "celery",
    "magic carpet",
    "barn",
    "pail",
    "squirt gun",
    "vase",
    "computer",
    "cannon",
    "magnet",
    "organ",
    "watch",
    "carpet",
    "swim",
    "sea turtle",
    "ribbon",
    "wreck",
    "watering can",
    "paper",
    "kettle",
    "bomb",
    "paw",
    "oar",
    "envelope",
    "sushi",
    "start",
    "plug",
    "pocket",
    "feast",
    "liquid",
    "tank",
    "rope",
    "picture frame",
    "maze",
    "glass",
    "jungle",
    "eraser",
    "ski",
    "latitude",
    "mask",
    "sunset",
    "well",
    "wing",
    "gravity",
    "tie",
    "desert",
    "pulley",
    "hot-air balloon",
    "subway",
    "mouse",
    "turkey",
    "window",
    "roof",
    "closed",
    "stocking",
    "target",
    "save",
    "ironing board",
    "cook",
    "art",
    "panda",
    "chess",
    "colored pencil",
    "sit",
    "cape",
    "sunburn",
    "fruit",
    "cast",
    "ice",
    "coconut",
    "fur",
    "horse",
    "swing",
    "bagpipe",
    "bathtub",
    "movie theater",
    "stamp",
    "porcupine",
    "escalator",
    "sidewalk",
    "dig",
    "melt",
    "tusk",
    "lucky",
    "garage",
    "money",
    "hospital",
    "bagel",
    "marry",
    "tooth",
    "heel",
    "grandma",
    "light switch",
    "slide",
    "zoo",
    "lipstick",
    "mailbox",
    "onion",
    "cheetah",
    "cougar",
    "pencil",
    "tail",
    "mattress",
    "hockey",
    "present",
    "robin",
    "anvil",
    "top hat",
    "chart",
    "babysitter",
    "pendulum",
    "face",
    "whistle",
    "umbrella",
    "cliff",
    "sunglasses",
    "bike",
    "sprinkler",
    "noon",
    "America",
    "backbone",
    "worm",
    "headband",
    "canoe",
    "kiss",
    "gumball",
    "throat",
    "campfire",
    "equator",
    "trap",
    "chalk",
    "helium",
    "playground",
    "princess",
    "lid",
    "surfboard",
    "spear",
    "tape",
    "frame",
    "mug",
    "pajamas",
    "soap",
    "crown",
    "farm",
    "needle",
    "bowtie",
    "class",
    "cake",
    "meat",
    "sail",
    "hairbrush",
    "shark",
    "compass",
    "bathroom scale",
    "time",
    "waffle",
    "milk",
    "harmonica",
    "clam",
    "glue",
    "shipwreck",
    "wrench",
    "empty",
    "free",
    "baby",
    "nature",
    "teacher",
    "zipper",
    "kitchen",
    "doctor",
    "food",
    "blue jeans",
    "teeth",
    "list",
    "graph",
    "marshmallow",
    "bushes",
    "jewelry",
    "crib",
    "gate",
    "smoke",
    "growl",
    "leak",
    "television",
    "squirrel",
    "pinwheel",
    "saddle",
    "bucket",
    "cotton candy",
    "sack",
    "banana split",
    "marker",
    "baseball",
    "wrist",
    "coal",
    "ship",
    "eagle",
    "wave",
    "golf",
    "hurdle",
    "rose",
    "birthday",
    "loaf",
    "lightsaber",
    "penny",
    "mouth",
    "pickle",
    "eclipse",
    "drumstick",
    "weight",
    "lighthouse",
    "hero",
    "mitten",
    "river",
    "purse",
    "screwdriver",
    "song",
    "skunk",
    "plate",
    "hopscotch",
    "storm",
    "toast",
    "tightrope",
    "rat",
    "scarf",
    "aircraft",
    "violin",
    "school bus",
    "nurse",
    "crater",
    "banjo",
    "cheerleader",
    "gold",
    "chest",
    "broccoli",
    "spaceship",
    "cardboard",
    "lock",
    "electricity",
    "yardstick",
    "popcorn",
    "clown",
    "store",
    "propeller",
    "batteries",
    "motorcycle",
    "printer",
    "hurricane",
    "button",
    "pan",
    "collar",
    "palace",
    "dragon",
    "peach",
    "plant",
    "telephone",
    "knight",
    "nut",
    "hole",
    "full moon",
    "fax",
    "jar",
    "rock",
    "fairies",
    "muscle",
    "cave",
    "sleeping bag",
    "butcher",
    "throne",
    "ceiling fan",
    "rib",
    "tadpole",
    "mirror",
    "east",
    "oil",
    "treasure",
    "rolly polly",
    "pelican",
    "sailboat",
    "tip",
    "skateboard",
    "merry-go-round",
    "porch",
    "log",
    "positive",
    "vest",
    "waist",
    "hip",
    "anemone",
    "laundry basket",
    "crayon",
    "janitor",
    "soccer",
    "base",
    "half",
    "zookeeper",
    "hair",
    "goldfish",
    "lifejacket",
    "apologize",
    "ping pong",
    "calendar",
    "cul-de-sac",
    "pollution",
    "globe",
    "pool",
    "sand",
    "farmer",
    "museum",
    "thermometer",
    "doorknob",
    "twig",
    "go",
    "bell pepper",
    "hourglass",
    "music",
    "lemon",
    "swimming pool",
    "spill",
    "address",
    "hill",
    "juice",
    "brain",
    "ask",
    "pineapple",
    "black widow",
    "tractor",
    "bald eagle",
    "snow",
    "dog leash",
    "alarm clock",
    "trampoline",
    "queen",
    "saxophone",
    "dress",
    "step",
    "yo-yo",
    "spell",
    "round",
    "banana peel",
    "rug",
    "zebra",
    "mail",
    "pillowcase",
    "puzzle",
    "hug",
    "hunter",
    "baggage",
    "pipe",
    "curtain",
    "razor",
    "run",
    "lap",
    "fin",
    "pogo stick",
    "elephant",
    "cricket",
    "toothbrush",
    "guitar",
    "maid",
    "coin",
    "helicopter",
    "wreath",
    "candle",
    "salt",
    "pot",
    "bib",
    "lung",
    "photograph",
    "corn",
    "wax",
    "thumb",
    "grape",
    "back",
    "family",
    "trip",
    "newspaper",
    "stroller",
    "artist",
    "homeless",
    "enter",
    "tire",
    "flute",
    "sneeze",
    "cell phone",
    "scientist",
    "magic",
    "pear",
    "daddy longlegs",
    "shake",
    "sponge",
    "trumpet",
    "wall",
    "key",
    "race car",
    "seesaw",
    "ladybug",
    "basket",
    "Ferris wheel",
    "whisk",
    "parachute",
    "knot",
    "thief",
    "goose",
    "desk",
    "battery",
    "children",
    "nest",
    "letter",
    "carousel",
    "bell",
    "reindeer",
    "timer",
    "poodle",
    "nail",
    "wagon",
    "door",
    "cowboy",
    "hammer",
    "garden",
    "jacket",
    "college",
    "draw",
    "hula hoop",
    "catfish",
    "boot",
    "potato",
    "plank",
    "sock",
    "shovel",
    "tulip",
    "dollar",
    "cocoon",
    "read",
    "buggy",
    "monster",
    "salt and pepper",
    "pine tree",
    "hoof",
    "paper clips",
    "sleeve",
    "tent",
    "clownfish",
    "blimp",
    "wheelchair",
    "stork",
    "solar system",
    "DVD",
    "angel",
    "light bulb",
    "chip",
    "tub",
    "pet",
    "smile",
    "jump",
    "iPad",
    "circus",
    "drill",
    "stapler",
    "airport",
    "chain",
    "wooly mammoth",
    "minivan",
    "giant",
    "drums",
    "goat",
    "submarine",
    "washing machine",
    "tennis",
    "camera",
    "baker",
    "notepad",
    "video camera",
    "eye patch",
    "shadow",
    "shower",
    "box",
    "manatee",
    "straw",
    "ambulance",
    "wick",
    "stingray",
    "pop",
    "attic",
    "doormat",
    "shopping cart",
    "faucet",
    "table",
    "ticket",
    "hot dog",
    "cello",
    "eel",
    "pea",
    "skirt",
    "three-toed sloth",
    "tricycle",
    "ocean",
    "library",
    "toy",
    "dinner",
    "bicycle",
    "contain",
    "elevator",
    "mold",
    "string",
    "pinecone",
    "restaurant",
    "cage",
    "howl",
    "necktie",
    "chocolate chip cookie",
    "park",
    "belt",
    "muffin",
    "lip",
    "roller blading",
    "frying pan",
    "crust",
    "ink",
    "safety goggles",
    "spine",
    "seashell",
    "skate",
    "shampoo",
    "detective",
    "king",
    "flood",
    "elbow",
    "fern"
]
var hardWords = [
    "miner",
    "dead end",
    "roller coaster",
    "albatross",
    "fiance",
    "orbit",
    "crate",
    "geologist",
    "stutter",
    "tourist",
    "stow",
    "compare",
    "elope",
    "bulldog",
    "thunder",
    "tip",
    "important",
    "optometrist",
    "drip",
    "sap",
    "pharmacist",
    "grasslands",
    "university",
    "hand soap",
    "black belt",
    "omnivore",
    "professor",
    "servant",
    "boa constrictor",
    "geyser",
    "turtleneck",
    "publisher",
    "boxing",
    "centimeter",
    "groom",
    "partner",
    "living room",
    "invent",
    "cockpit",
    "putty",
    "mysterious",
    "humidity",
    "art gallery",
    "oxcart",
    "ringleader",
    "wallow",
    "shrew",
    "telephone booth",
    "synchronized swimming",
    "videogame",
    "sweater",
    "cherub",
    "palace",
    "zoom",
    "sunrise",
    "ticket",
    "sweater vest",
    "point",
    "parent",
    "garden hose",
    "limit",
    "mine",
    "song",
    "vein",
    "pocket",
    "fade",
    "trail",
    "chess",
    "reveal",
    "foil",
    "snooze",
    "government",
    "download",
    "signal",
    "glue stick",
    "leak",
    "accounting",
    "great-grandfather",
    "pizza sauce",
    "Jedi",
    "yawn",
    "bald",
    "barber",
    "runt",
    "barbershop",
    "landlord",
    "Quidditch",
    "think",
    "cabin",
    "skating rink",
    "movie",
    "cardboard",
    "yodel",
    "attack",
    "dawn",
    "chariot",
    "diver",
    "stay",
    "ditch",
    "icicle",
    "economics",
    "costume",
    "juggle",
    "learn",
    "yardstick",
    "aunt",
    "page",
    "poison",
    "sun block",
    "character",
    "cream",
    "flu",
    "staple",
    "dance",
    "zipper",
    "atlas",
    "best friend",
    "win",
    "blush",
    "disc jockey",
    "sushi",
    "delivery",
    "apathetic",
    "chime",
    "caviar",
    "heater",
    "drill bit",
    "fortress",
    "post office",
    "florist",
    "Internet",
    "toll road",
    "pro",
    "carpet",
    "human",
    "swing dancing",
    "factory",
    "lullaby",
    "bride",
    "chariot racing",
    "pickup truck",
    "applause",
    "gasoline",
    "speakers",
    "prize",
    "wool",
    "spare",
    "saddle",
    "chameleon",
    "password",
    "snore",
    "testify",
    "propose",
    "date",
    "toddler",
    "goblin",
    "mat",
    "clique",
    "amusement park",
    "athlete",
    "conveyor belt",
    "logo",
    "traffic jam",
    "pest",
    "brand",
    "macaroni",
    "bargain",
    "foam",
    "chestnut",
    "gallon",
    "pet store",
    "biscuit",
    "cure",
    "wooly mammoth",
    "swamp",
    "jigsaw",
    "lace",
    "seat",
    "comfy",
    "competition",
    "expert",
    "dizzy",
    "cuckoo clock",
    "taxidermist",
    "trombone",
    "sleep",
    "log-in",
    "concession stand",
    "sword swallower",
    "musician",
    "vacation",
    "hydrogen",
    "fireman pole",
    "toolbox",
    "spaceship",
    "wheelie",
    "raft",
    "weather",
    "husband",
    "ivy",
    "double",
    "hail",
    "electrical outlet",
    "hour",
    "midnight",
    "yolk",
    "clamp",
    "coach",
    "dress shirt",
    "president",
    "ratchet",
    "sticky note",
    "retail",
    "eighteen-wheeler",
    "produce",
    "hot tub",
    "welder",
    "knight",
    "RV",
    "bonnet",
    "print",
    "bruise",
    "carnival",
    "ski lift",
    "vehicle",
    "prime meridian",
    "firefighter",
    "injury",
    "ski goggles",
    "snarl",
    "quartz",
    "end zone",
    "migrate",
    "cleaning spray",
    "scream",
    "van",
    "right",
    "jazz",
    "chain mail",
    "tide",
    "cubicle",
    "cowboy",
    "cattle",
    "first class",
    "beluga whale",
    "correct",
    "postcard",
    "dentist",
    "tank",
    "yacht",
    "eraser",
    "owner",
    "loveseat",
    "water cycle",
    "rib",
    "obey",
    "recycle",
    "salmon",
    "fur",
    "avocado",
    "kneel",
    "rubber",
    "mayor",
    "robe",
    "last",
    "shack",
    "bleach",
    "germ",
    "plow",
    "stationery",
    "back flip",
    "mold",
    "crop duster",
    "sneeze",
    "myth",
    "cloak",
    "headache",
    "dent",
    "snag",
    "jeans",
    "tow truck",
    "carpenter",
    "hut",
    "s'mores",
    "clog",
    "vanish",
    "wedding cake",
    "sponge",
    "leather",
    "koala",
    "fireside",
    "recess",
    "jaw",
    "dryer sheets",
    "prey",
    "photosynthesis",
    "gold",
    "parking garage",
    "shrink ray",
    "baguette",
    "wrap",
    "laundry detergent",
    "plumber",
    "fiddle",
    "vet",
    "mascot",
    "steam",
    "calm",
    "grocery store",
    "drugstore",
    "roommate",
    "manatee",
    "banister",
    "tow",
    "nightmare",
    "flavor",
    "molar",
    "frost",
    "cushion",
    "receipt",
    "reservoir",
    "homework",
    "stuffed animal",
    "advertisement",
    "team",
    "trip",
    "student",
    "sunburn",
    "somersault",
    "pawn",
    "hoop",
    "boulevard",
    "volleyball",
    "baby-sitter",
    "fizz",
    "wag",
    "tackle",
    "puppet",
    "sandpaper",
    "whisk",
    "level",
    "torch",
    "punk",
    "tugboat",
    "police",
    "stage",
    "vegetarian",
    "distance",
    "rhythm",
    "sandbox",
    "yak",
    "arcade",
    "baggage",
    "sash",
    "cell phone charger",
    "tablespoon",
    "dripping",
    "time",
    "yard",
    "drawback",
    "pharaoh",
    "nap",
    "junk",
    "sheep dog",
    "sugar",
    "hairspray",
    "cable car",
    "golf cart",
    "ruby",
    "stadium",
    "letter opener",
    "deep",
    "full",
    "bookend",
    "pain",
    "houseboat",
    "gold medal",
    "elf",
    "downpour",
    "density",
    "rim",
    "honk",
    "ceiling fan",
    "monsoon",
    "pail",
    "company",
    "devious",
    "coworker",
    "connection",
    "blueprint",
    "softball",
    "wobble",
    "cheerleader",
    "runoff",
    "ounce",
    "taxi",
    "wind",
    "quicksand",
    "twist",
    "cot",
    "carat",
    "printer ink",
    "acrobat",
    "interception",
    "darkness",
    "macho",
    "world",
    "plantation",
    "fabric",
    "hang glider",
    "sled",
    "classroom",
    "chairman",
    "school",
    "tiptoe",
    "cruise",
    "science",
    "parade",
    "landscape",
    "lipstick",
    "drain",
    "rudder",
    "cape",
    "Heinz 57",
    "fresh water",
    "cheat",
    "braid",
    "dashboard",
    "thrift store",
    "commercial",
    "grandpa",
    "ashamed",
    "engaged",
    "extension cord",
    "car dealership",
    "ream",
    "bobsled",
    "drive-through",
    "irrigation",
    "wax",
    "vitamin",
    "time machine",
    "mirror",
    "hurdle",
    "haircut",
    "gas station",
    "cartoon",
    "lunch tray",
    "quadrant",
    "balance beam",
    "toy store",
    "beanstalk",
    "tearful",
    "darts",
    "son-in-law",
    "picnic",
    "check",
    "customer",
    "quit",
    "rut",
    "religion",
    "cough",
    "cargo",
    "half",
    "record",
    "cousin",
    "wig",
    "water buffalo",
    "birthday",
    "pile",
    "trapped",
    "glitter",
    "stopwatch",
    "season",
    "suit",
    "edit",
    "chemical",
    "fog",
    "swarm",
    "hospital",
    "deliver",
    "script",
    "swoop",
    "crime",
    "lecture",
    "crow's nest",
    "diagonal",
    "moth",
    "country",
    "washing machine",
    "cliff",
    "gown",
    "dream",
    "plank",
    "coastline",
    "hermit crab",
    "freshman",
    "jungle",
    "driveway",
    "safe",
    "dorsal",
    "guarantee",
    "tin",
    "mime",
    "CD",
    "scuba diving",
    "pilot",
    "newsletter",
    "edge",
    "rodeo",
    "crust",
    "border",
    "scuff mark",
    "dust bunny",
    "fast food",
    "story",
    "soak",
    "laser",
    "lung",
    "truck stop",
    "plastic",
    "idea",
    "passenger",
    "glue gun",
    "lunar rover",
    "toothpaste",
    "exercise",
    "coil",
    "surround",
    "actor",
    "baseboards",
    "aircraft carrier",
    "catalog",
    "degree",
    "vanilla",
    "lumberyard",
    "bedbug",
    "neighborhood",
    "earache",
    "peace",
    "goalkeeper",
    "zoo",
    "bookstore",
    "ornament",
    "cellar",
    "dodgeball",
    "dew",
    "cliff diving",
    "ping pong",
    "chef",
    "clown",
    "imagine",
    "shelter",
    "mast",
    "thaw",
    "airport security",
    "lie",
    "flock",
    "captain",
    "stew",
    "gumball",
    "stage fright",
    "handle",
    "taxes",
    "cello",
    "shampoo",
    "nanny",
    "cruise ship",
    "lap",
    "crane",
    "shower curtain",
    "blizzard",
    "earthquake",
    "chisel",
    "oar",
    "rind",
    "ginger",
    "front",
    "hipster",
    "drought",
    "lance",
    "startup",
    "thief",
    "violent",
    "pigpen",
    "judge",
    "organ",
    "chicken coop",
    "hovercraft",
    "peasant",
    "tag"
  ]
var veryHardWords = [
    "inning",
    "doubtful",
    "vision",
    "ornithologist",
    "rhythm",
    "tutor",
    "promise",
    "trademark",
    "first mate",
    "silt",
    "scalawag",
    "feeder road",
    "emperor",
    "parley",
    "paranoid",
    "pawnshop",
    "regret",
    "deceive",
    "aftermath",
    "steamboat",
    "fowl",
    "treatment",
    "feeling",
    "mayhem",
    "gentleman",
    "parody",
    "observatory",
    "bushel",
    "demanding",
    "admire",
    "guru",
    "reaction",
    "brunette",
    "crew",
    "wetlands",
    "license",
    "wish",
    "destination",
    "member",
    "landfill",
    "name",
    "doubloon",
    "Chick-fil-A",
    "lichen",
    "writhe",
    "chaos",
    "fragment",
    "opaque",
    "sapphire",
    "exponential",
    "default",
    "pastry",
    "schedule",
    "infection",
    "aristocrat",
    "society",
    "income",
    "chord",
    "insurance",
    "big bang theory",
    "condition",
    "shame",
    "income tax",
    "clue",
    "guess",
    "prepare",
    "hypothermia",
    "Zen",
    "nutmeg",
    "refund",
    "stowaway",
    "comparison",
    "sickle",
    "lyrics",
    "emigrate",
    "VIP",
    "courthouse",
    "figment",
    "doppelganger",
    "compromise",
    "armada",
    "decipher",
    "representative",
    "dugout",
    "today",
    "zone defense",
    "enemy",
    "confidant",
    "password",
    "hearse",
    "czar",
    "stockholder",
    "pen pal",
    "standing ovation",
    "handful",
    "voice",
    "rest stop",
    "hang ten",
    "tug",
    "discovery",
    "improve",
    "wealth",
    "water vapor",
    "group",
    "cause",
    "slam dunk",
    "memory",
    "copyright",
    "psychologist",
    "tinting",
    "protestant",
    "flight",
    "slump",
    "offstage",
    "form",
    "ligament",
    "descendant",
    "castaway",
    "digestion",
    "effect",
    "panic",
    "philosopher",
    "temper",
    "swag",
    "drift",
    "upgrade",
    "mine car",
    "villain",
    "punishment",
    "texture",
    "cloudburst",
    "carat",
    "navigate",
    "cramp",
    "blacksmith",
    "destruction",
    "language",
    "dispatch",
    "convenience store",
    "rainwater",
    "problem",
    "pride",
    "inquisition",
    "quiver",
    "blueprint",
    "county fair",
    "periwinkle",
    "fad",
    "leap year",
    "fun house",
    "loiterer",
    "duvet",
    "employee",
    "property",
    "disgust",
    "risk",
    "intern",
    "wormhole",
    "gravel",
    "riddle",
    "kilogram",
    "jig",
    "mortal",
    "rhyme",
    "index",
    "reward",
    "sidekick",
    "history",
    "dictate",
    "friction",
    "channel",
    "reimbursement",
    "voicemail",
    "tribe",
    "education",
    "plot",
    "implode",
    "century",
    "stagecoach",
    "remain",
    "cranium",
    "gondola",
    "incisor",
    "junk drawer",
    "try",
    "con",
    "climate",
    "freshwater",
    "positive",
    "forklift",
    "brainstorm",
    "welder",
    "flutter",
    "credit",
    "resourceful",
    "tattle",
    "dud",
    "cartoonist",
    "P.O. box",
    "companion",
    "hay wagon",
    "one-way street",
    "scatter",
    "community",
    "crisp",
    "ironic",
    "creator",
    "sleet",
    "buccaneer",
    "twang",
    "whiplash",
    "pelt",
    "pomp",
    "snag",
    "publisher",
    "retire",
    "neutron",
    "stranger",
    "good-bye",
    "fathom",
    "organization",
    "realm",
    "diversify",
    "interference",
    "zero",
    "grain",
    "president",
    "occupant",
    "knowledge",
    "mortified",
    "Atlantis",
    "population",
    "stun",
    "acoustics",
    "flotsam",
    "layover",
    "haberdashery",
    "smidgen",
    "confide",
    "ma'am",
    "detail",
    "system",
    "hobby",
    "stuff",
    "tournament",
    "cartography",
    "apparatus",
    "translate",
    "turret",
    "statement",
    "wasabi",
    "expired",
    "practice",
    "gymnast",
    "fake flowers",
    "joke",
    "fun",
    "cover",
    "stout",
    "opinion",
    "cutlass",
    "theory",
    "random",
    "ice fishing",
    "transpose",
    "champion",
    "telepathy",
    "cashier",
    "soulmate",
    "profit",
    "galaxy",
    "title",
    "acre",
    "doubt",
    "committee",
    "zip code",
    "bed and breakfast",
    "fuel",
    "steel drum",
    "food court",
    "sophomore",
    "archaeologist",
    "inertia",
    "irrational",
    "coast",
    "soul",
    "in-law",
    "vanquish",
    "siesta",
    "preteen",
    "interject",
    "rival",
    "trawler",
    "ray",
    "quarantine",
    "overture",
    "depth",
    "gallop",
    "mooch",
    "consent",
    "exhibition",
    "semester",
    "cubit",
    "error",
    "dryer sheet",
    "Everglades",
    "eureka",
    "time zone",
    "danger",
    "infect",
    "altitude",
    "crow's nest",
    "blunt",
    "debt"
  ]
words = [...easyWords,...mediumWords,...hardWords,...veryHardWords]
function genorateListOfWords(count){
    var c = count || 1;
    var out = []
    while(c > 0){
        var randomWord = words[Math.floor(Math.random() * words.length)]
        if(out.indexOf(randomWord) == -1){
            out.push(randomWord);
            c--;

        }
    }
    return out;
}

export {genorateListOfWords, words};